import "./globals.css";
import type { Metadata } from "next";
import { Inter,Saira_Stencil_One,Spicy_Rice} from "next/font/google";
import localFont from 'next/font/local'
import NavBar from "./NavBar";
import AuthProvider from "./auth/Provider";
import GoogleAnalyticsScript from "./GoogleAnalyticsScript";

const inter = Inter({ subsets: ["latin"] });
 const rock = Spicy_Rice({
  subsets:['latin'],
  weight:['400']
 })
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="winter">
      <GoogleAnalyticsScript/>
      <body className={rock.className}>
        <AuthProvider>
          <NavBar />
          <main className="bg-slate-100 p-5">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
